name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true
      - name: Bower
        run: |
          npm install -g bower
          bower install
      - name: Build site
        run: |
          bundle exec jekyll build 2> error.log
          cat >&2 error.log
          ( ! grep -qie Error -e Warn error.log )
      - name: Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v4
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer
      - name: HTMLProofer
        run: |
          # Check all links
          # Don't check links to twitter.com because they return 400 all the time
          # Also ignore github.com because we have too many and they eventually return 429
          bundle exec htmlproofer ./_site/\
             --only-4xx\
             --ignore-empty-alt\
             --allow-hash-href\
             --no-enforce-https\
             --ignore-missing-alt\
             --swap-urls "https\:\/\/scala\.epfl\.ch:"\
             --ignore-urls "/twitter.com/,/x.com/,/github.com/"\
             --cache '{ "timeframe": { "external": "30d" } }'
